name: pc1500
version: 0.1.0
description: Sharp PC-1500 pocket computer emulator.
homepage: https://github.com/cbonello/
repository: https://github.com/cbonello/pc1500
issue_tracker: https://github.com/cbonello/pc1500/issues
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.0
  device:
    path: packages/device
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  just_audio: ^0.10.5
  lcd:
    path: packages/lcd
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
  lint: ^2.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/systems/
    - assets/docs/
