name: pc1500
version: 0.1.0
description: Sharp PC-1500 pocket compter emulator.
author: Christophe Bonello
homepage: https://github.com/cbonello/
repository: https://github.com/cbonello/pc1500
issue_tracker: https://github.com/cbonello/pc1500/issues
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  system:
    path: packages/system
  bitsdojo_window: ^0.0.0
  cupertino_icons: ^1.0.0
  hooks_riverpod: ^0.12.0
  json_annotation: ^3.1.0
  web_socket_channel: ^1.1.0

dev_dependencies:
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.0
  lint: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/systems/
