name: pc1500
version: 0.1.0
description: Sharp PC-1500 pocket compter emulator.
author: Christophe Bonello
homepage: https://github.com/cbonello/
repository: https://github.com/cbonello/pc1500
issue_tracker: https://github.com/cbonello/pc1500/issues

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter
  system:
    path: packages/system

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/

