name: lh5811
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  freezed_annotation: ^0.11.0
  meta: any

dev_dependencies:
  build_runner: ^1.10.0
  freezed: ^0.11.0
  lint: ^1.2.0
  test: ^1.14.0
