name: roms_example
description: ROMs example.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  annotations:
    path: ../../annotations
  roms:
    path: ../../roms

dev_dependencies:
  lint: ^1.2.0
  test: ^1.14.4

