name: lcd
version: 0.1.0
description: LCD driver for the Sharp PC-1500 pocket-computer.
author: Christophe Bonello
homepage: https://github.com/cbonello/
repository: https://github.com/cbonello/pc1500/tree/master/packages/lcd
issue_tracker: https://github.com/cbonello/pc1500/issues
publish_to: none

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  chip_select_decoder:
    path: ../chip_select_decoder
  meta: any

dev_dependencies:
  lint: ^1.5.0
  test: ^1.14.0
