name: chip_select_decoder
version: 0.1.0
description: Implements the chip-select decoder of a Sharp PC-1500 pocket computer.
author: Christophe Bonello
homepage: https://github.com/cbonello/
repository: https://github.com/cbonello/pc1500/tree/master/packages/chip_select_decoder
issue_tracker: https://github.com/cbonello/pc1500/issues

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  equatable: ^1.2.0
  meta: ^1.2.0

dev_dependencies:
  lint: ^1.2.0
  mockito: ^4.1.0
  test: ^1.14.0
  test_coverage: ^0.4.0

