name: roms
version: 0.1.0
description: Sharp PC-1500 pocket compter ROMs.
author: Christophe Bonello
homepage: https://github.com/cbonello/
repository: https://github.com/cbonello/pc1500/tree/master/packages/roms
issue_tracker: https://github.com/cbonello/pc1500/issues

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  args: ^1.6.0
  meta: ^1.1.0
  path: ^1.7.0

dev_dependencies:
  crypto: ^2.1.0
  lint: ^1.2.0
  test: ^1.14.0

