name: system
version: 0.1.0
description: Sharp PC-1500 pocket-computer emulator.
author: Christophe Bonello
homepage: https://github.com/cbonello/
repository: https://github.com/cbonello/pc1500/tree/master/packages/system
issue_tracker: https://github.com/cbonello/pc1500/issues

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  chip_select_decoder:
    path: ../chip_select_decoder
  lh5801:
    git:
      url: https://github.com/cbonello/lh5801.git
  meta: ^1.1.0
  roms:
    path: ../roms

dev_dependencies:
  lint: ^1.2.0
  test: ^1.14.0
  test_coverage: ^0.4.0

